"""add class levels and client posts

Revision ID: 153ab6850d85
Revises: 6a210b49fda9
Create Date: 2026-10-08 12:07:23.525627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153ab6850d85'
down_revision: Union[str, Sequence[str], None] = '6a210b49fda9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Enum('preschool', 'elementary', 'intermediate', 'secondary', 'higher_education', name='education_level'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_class_levels_id'), 'class_levels', ['id'], unique=False)
    op.create_index(op.f('ix_class_levels_level'), 'class_levels', ['level'], unique=False)
    op.create_table('client_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('class_level_id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='post_status'), server_default='active', nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('address_details', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_level_id'], ['class_levels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_posts_class_level_id'), 'client_posts', ['class_level_id'], unique=False)
    op.create_index(op.f('ix_client_posts_client_id'), 'client_posts', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_posts_id'), 'client_posts', ['id'], unique=False)
    op.create_index(op.f('ix_client_posts_status'), 'client_posts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_posts_status'), table_name='client_posts')
    op.drop_index(op.f('ix_client_posts_id'), table_name='client_posts')
    op.drop_index(op.f('ix_client_posts_client_id'), table_name='client_posts')
    op.drop_index(op.f('ix_client_posts_class_level_id'), table_name='client_posts')
    op.drop_table('client_posts')
    op.drop_index(op.f('ix_class_levels_level'), table_name='class_levels')
    op.drop_index(op.f('ix_class_levels_id'), table_name='class_levels')
    op.drop_table('class_levels')
    # ### end Alembic commands ###
