"""add summary to tutor profiles

Revision ID: 6a210b49fda9
Revises: 319a1f7d4d58
Create Date: 2026-10-08 11:38:11.402077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a210b49fda9'
down_revision: Union[str, Sequence[str], None] = '319a1f7d4d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor_profiles', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutor_profiles', 'summary')
    # ### end Alembic commands ###
